function G = functionG(L2,Lcom2,Lcom3,m2,m3,q2,q3)
%functionG
%    G = functionG(L2,Lcom2,Lcom3,M2,M3,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    16-Apr-2023 13:16:22

t2 = cos(q2);
t3 = q2+q3;
t4 = cos(t3);
t5 = Lcom3.*m3.*t4.*-9.806650000000445;
t6 = Lcom3.*m3.*t4.*9.806650000000445;
G = [0.0;t5-L2.*m3.*t2.*9.806650000000445-Lcom2.*m2.*t2.*9.806650000000445;t5];
